prevent windows php8 tests as there is no libfuzzy

diff --git a/.github/workflows/build-test-and-release.yml b/.github/workflows/build-test-and-release.yml
--- a/.github/workflows/build-test-and-release.yml
+++ b/.github/workflows/build-test-and-release.yml
@@ -3,12 +3,25 @@ name: Build, test and Release PECL Extension
 on:
   push:
     tags:
-      - "v*.*.*" # Trigger on version tags
+      - "*.*.*" # Trigger on version tags
     branches:
       - master
   workflow_dispatch: # Allows manual trigger
 
 jobs:
+  check_version:
+    runs-on: ubuntu-latest
+    if: startsWith(github.ref, 'refs/tags/') # Ensure it's a tag
+    steps:
+      - name: Check if tag is a valid version
+        run: |
+          TAG_NAME=$(echo "${GITHUB_REF#refs/tags/}")
+          if [[ ! "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Tag '$TAG_NAME' does not match semantic versioning format."
+            exit 1
+          fi
+          echo "Tag '$TAG_NAME' is a valid version."
+
   build-linux:
     runs-on: ubuntu-latest
     strategy:
@@ -35,7 +48,6 @@ jobs:
         uses: shivammathur/setup-php@v2
         with:
           php-version: ${{ matrix.php-version }}
-          tools:
 
       - name: Install dependencies
         run: |
@@ -58,7 +70,9 @@ jobs:
       fail-fast: false
       matrix:
         os: [windows-2019, windows-latest]
-        php-version: ["7.4", "8.0"] #, "8.1", "8.2", "8.3"]
+        # not testing on PHP8 for windows at the moment because there is no libfuzzy dependency
+        # compiled for it
+        php-version: ["7.4"] #, "8.0", "8.1", "8.2", "8.3"]
         arch: [x64, x86]
         ts: [nts, ts]
         exclude:
